version: '3.9'
name: stc
services:
  sql-db:
    image: mysql:8.0
    container_name: sql-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - ../visitas/infraestructura/esquema/Setup_Visita_DB.sql:/docker-entrypoint-initdb.d/Setup_Visita_DB.sql
      - ../notificaciones/infraestructura/esquema/Setup_Notif_DB.sql:/docker-entrypoint-initdb.d/Setup_Notif_DB.sql
      - ../autenticacion/infraestructura/esquema/micro_login.sql:/docker-entrypoint-initdb.d/micro_login.sql
      - ../incidentes/infraestructura/esquema/g5_gestact.sql:/docker-entrypoint-initdb.d/g5_gestact.sql
      - ../incidentes/infraestructura/esquema/g5_mock_act_data.sql:/docker-entrypoint-initdb.d/g5_mock_act_data.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 3

  visitas:
    build:
      context: ../visitas
      dockerfile: ../docker/Dockerfile
    container_name: visitas
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - "PORT=${PORT_1}"
      - "API_INCID=http://incidentes:8005/incidentes"
      - "API_TECN=http://tecnicos:8004/technicians"
    ports:
      - "${PORT_1}:${PORT_1}"
    depends_on:
      - "sql-db"
    networks:
      - backend

  notif:
    build:
      context: ../notificaciones
      dockerfile: ../docker/Dockerfile
    container_name: notif
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - "PORT=${PORT_2}"
    ports:
      - "${PORT_2}:${PORT_2}"
    depends_on:
      - "sql-db"
    networks:
      - backend

  auth:
    build:
      context: ../autenticacion
      dockerfile: ../docker/Dockerfile
    container_name: auth
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - "PORT=${PORT_3}"
      - "TECNICO_API=http://tecnicos:8004/technicians"
    ports:
      - "${PORT_3}:${PORT_3}"
    depends_on:
      - "sql-db"
    networks:
      - backend

  tecnicos:
    build:
      context: ../tecnicos
      dockerfile: ../docker/Dockerfile
    container_name: tecnicos
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - "APP_PORT=${PORT_4}"
    ports:
      - "${PORT_4}:${PORT_4}"
    depends_on:
      sql-db:
        condition: service_healthy
    networks:
      - backend

  incidentes:
    build:
      context: ../incidentes
      dockerfile: ../docker/Dockerfile
    container_name: incidentes
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - "PORT=${PORT_5}"
    ports:
      - "${PORT_5}:${PORT_5}"
    depends_on:
      sql-db:
        condition: service_healthy
    networks:
      - backend
    
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: unless-stopped
    depends_on:
      - "visitas"
      - "notif"
      - "auth"
      - "tecnicos"
      - "incidentes"
    ports:
      - "80:80"
    networks:
      - backend

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - "sql-db"
    networks:
      - backend

networks:
  backend:
    driver: bridge